### ISSUE TITLE
Submission TODO

### ISSUE THREAD

**Issue by TanyaS08** [PoisotLab/ms_metaweb_perspectives#1]
- [x] Check Cover letter
- [ ] Add DOI for preprint (in cover letter and submission platform
- [x] Journal suitability statement thing-y
- [x] Final word count
- [ ] Suggested reviewers & Editor
